name: CI

on: [push, workflow_dispatch]

jobs:


  build:


    runs-on: windows-latest


    steps:


    - name: Download


      run: curl -sLkO https://raw.githubusercontent.com/cdnss/rdp-NoMachine/main/nomachine-mate.sh ; bash nomachine-mate.sh


    
